// @generated by tools/build_pbr_details.py; do not edit.
// Decoded means are derived from the checked-in PNG bytes.

pub(crate) const CONCRETE_ALBEDO_LINEAR_MEAN: f32 = 0.879685563839;
pub(crate) const FOLIAGE_ALBEDO_LINEAR_MEAN: f32 = 0.912803028298;
pub(crate) const TRAFFIC_PAINT_ALBEDO_LINEAR_MEAN: f32 = 0.909307434653;
pub(crate) const TRAFFIC_PAINT_ROUGHNESS_LINEAR_MEAN: f32 = 0.929585415709;
